default_agent: backend_app_agents_bedrock_agent_bedrock_agent
agents:
  backend_app_agents_bedrock_agent_bedrock_agent:
    name: backend_app_agents_bedrock_agent_bedrock_agent
    entrypoint: C:/Users/User/Desktop/necessitas.ai/backend/app/agents/bedrock_agent/bedrock_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\User\Desktop\necessitas.ai\backend\app\agents\bedrock_agent
    aws:
      execution_role: arn:aws:iam::355444226013:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-a7b1b4288f
      execution_role_auto_create: false
      account: '355444226013'
      region: us-east-1
      ecr_repository: 355444226013.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-backend_app_agents_bedrock_agent_bedrock_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: backend_app_agents_bedrock_agent_bedrock_agent-MpIxw05WSx
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:355444226013:runtime/backend_app_agents_bedrock_agent_bedrock_agent-MpIxw05WSx
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-backend_app_agents_bedrock_agent_bedrock_agent-builder
      execution_role: arn:aws:iam::355444226013:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-a7b1b4288f
      source_bucket: bedrock-agentcore-codebuild-sources-355444226013-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: null
      memory_arn: null
      memory_name: backend_app_agents_bedrock_agent_bedrock_agent_memory
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
