repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: Remove trailing whitespace
        description: This hook trims whitespace.
        entry: trailing-whitespace-fixer
        language: python
        types: [text]
        exclude: |
          (?x)^(
            \.md$|
            \.txt$|
            \.rst$
          )$

      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures that a file is either empty or ends with one newline.
        entry: end-of-file-fixer
        language: python
        types: [text]

      - id: check-yaml
        name: Check YAML syntax
        description: This hook checks yaml files for parseable syntax.
        entry: check-yaml
        language: python
        types: [yaml]

      - id: check-json
        name: Check JSON syntax
        description: This hook checks json files for parseable syntax.
        entry: check-json
        language: python
        types: [json]

      - id: check-merge-conflict
        name: Check for merge conflict markers
        description: Check for files that contain merge conflict strings.
        entry: check-merge-conflict
        language: python
        types: [text]

      - id: check-added-large-files
        name: Check for large files
        description: Prevent large files from being committed.
        entry: check-added-large-files
        language: python
        args: ['--maxkb=1000']

  # Code quality hooks removed - run manually with ./scripts/auto-format.sh
  # or use CI warnings instead of blocking commits
