default_agent: bedrock_agent
agents:
  bedrock_agent:
    name: bedrock_agent
    entrypoint: C:/Users/User/Desktop/necessitas.ai/backend/app/agents/bedrock_agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: C:\Users\User\Desktop\necessitas.ai\backend\app\agents
    aws:
      execution_role: arn:aws:iam::355444226013:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-b0f5e41dff
      execution_role_auto_create: false
      account: '355444226013'
      region: us-east-1
      ecr_repository: 355444226013.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-bedrock_agent
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: bedrock_agent-VLBeXl6Jo1
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:355444226013:runtime/bedrock_agent-VLBeXl6Jo1
      agent_session_id: f9b9af51-b4e9-4932-9923-60fb508910d0
    codebuild:
      project_name: bedrock-agentcore-bedrock_agent-builder
      execution_role: arn:aws:iam::355444226013:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-b0f5e41dff
      source_bucket: bedrock-agentcore-codebuild-sources-355444226013-us-east-1
    memory:
      mode: STM_ONLY
      memory_id: bedrock_agent_mem-82H1owGzOp
      memory_arn: arn:aws:bedrock-agentcore:us-east-1:355444226013:memory/bedrock_agent_mem-82H1owGzOp
      memory_name: bedrock_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
