name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # Node.js setup removed - no frontend in current project structure

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pre-commit

    - name: Run code quality checks (warnings only)
      run: |
        echo "Running code quality checks (warnings only)..."
        python -m black . --check --diff || echo "⚠️ Black formatting issues found (warning only)"
        python -m isort . --check-only --diff || echo "⚠️ Import sorting issues found (warning only)"
        python -m flake8 . || echo "⚠️ Flake8 linting issues found (warning only)"
        echo "Code quality checks completed (warnings only)"

    - name: Run Python tests
      run: |
        echo "Running Python tests..."
        python tests/run_tests.py
        echo "Python tests completed"

  security-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install bandit safety

    - name: Run Bandit security scan
      run: bandit -r backend/ -f json -o bandit-report.json
      continue-on-error: true

    - name: Run Safety check
      run: safety check --json --output safety-report.json
      continue-on-error: true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          bandit-report.json
          safety-report.json

  # aws-deploy:
  #   runs-on: ubuntu-latest
  #   needs: [lint-and-test, security-scan]
  #   if: github.ref == 'refs/heads/main'

  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Set up Python
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: '3.11'

  #   # Node.js setup removed - no frontend in current project structure

  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install -r requirements.txt
  #       # npm install -g aws-cdk  # Removed - no frontend

  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: us-east-1

  #   - name: Deploy infrastructure
  #     run: |
  #       echo "Infrastructure deployment would go here"
  #       # python scripts/deploy.sh --region us-east-1

  #   - name: Run health checks
  #     run: |
  #       echo "Health checks would go here"
  #       # python scripts/health_check.py --region us-east-1
